language: go

go:
  - 1.12.x

services:
  - redis
  - mongodb

env:
  global:
    - MONGODB_URL=mongodb://localhost/shortener
    - MONGODB_TIMEOUT=30
    - MONGODB_DATABASE=shortener
    - REDIS_URL=redis://localhost:6379

before_install:
  - go get

script:
  - make test
