language: go

go:
  - 1.12.x

services:
  - redis
  - mongodb

env:
  - MONGODB_URL=mongodb://localhost/shortener
  - MONGODB_TIMEOUT=30
  - MONGODB_DATABASE=shortener
  - REDIS_URL=redis://localhost:6379

script:
  - make test
