// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import shortener "github.com/allisson/go-url-shortener"

// RedirectService is an autogenerated mock type for the RedirectService type
type RedirectService struct {
	mock.Mock
}

// Find provides a mock function with given fields: code
func (_m *RedirectService) Find(code string) (*shortener.Redirect, error) {
	ret := _m.Called(code)

	var r0 *shortener.Redirect
	if rf, ok := ret.Get(0).(func(string) *shortener.Redirect); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shortener.Redirect)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: redirect
func (_m *RedirectService) Store(redirect *shortener.Redirect) error {
	ret := _m.Called(redirect)

	var r0 error
	if rf, ok := ret.Get(0).(func(*shortener.Redirect) error); ok {
		r0 = rf(redirect)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
